---
version: '3'

networks:
  proxy:
    external: true

services:
  pihole:
    cap_add:
      - NET_ADMIN
    container_name: pihole
    environment:
      DNSMASQ_LISTENING: all
      FTLCONF_LOCAL_IPV4: ${HOST_IP_ADDRESS}
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      TZ: ${TIMEZONE}
      VIRTUAL_HOST: pihole.${DOMAIN}
      WEBPASSWORD: ''
    image: pihole/pihole:2023.05.2
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.pihole-secure.entrypoints=websecure
      - traefik.http.routers.pihole-secure.rule=Host(`pihole.${DOMAIN}`)
      - traefik.http.routers.pihole-secure.service=pihole
      - traefik.http.routers.pihole-secure.tls=true
      - traefik.http.routers.pihole-secure.tls.certresolver=cloudflare
      - traefik.http.services.pihole.loadbalancer.server.port=80
    networks:
      - proxy
    ports:
      - ${HOST_IP_ADDRESS}:53:53/tcp
      - ${HOST_IP_ADDRESS}:53:53/udp
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME}/pihole:/etc/pihole:rw
      - ${DOCKER_VOLUME}/dnsmasq.d:/etc/dnsmasq.d:rw
