version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'America/Vancouver'
      WEBPASSWORD: ''
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      VIRTUAL_HOST: pihole.serverly.ca
      DNSMASQ_LISTENING: all
      FTLCONF_LOCAL_IPV4: 192.168.1.225
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/pihole/pihole:/etc/pihole:rw
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=http"
      - "traefik.http.routers.pihole.rule=Host(`pihole.serverly.ca`)"
      - "traefik.http.middlewares.pihole-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pihole.middlewares=pihole-https-redirect"
      - "traefik.http.routers.pihole-secure.entrypoints=https"
      - "traefik.http.routers.pihole-secure.rule=Host(`pihole.serverly.ca`)"
      - "traefik.http.routers.pihole-secure.tls=true"
      - "traefik.http.routers.pihole-secure.service=pihole"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy" # Required when there is more than one network. More info at https://stackoverflow.com/a/73159943

networks: 
  proxy:
    external: true