version: '3'

# More info at https://docs.technotim.live/posts/traefik-portainer-ssl/ and https://www.youtube.com/watch?v=liV3c9m_OX8
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    env_file:
      - cloudflare.env
      - traefik.env
    environment:
      - CF_API_EMAIL=ericribeiro@outlook.com.br
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/traefik/:/etc/traefik
    labels:
      - "traefik.enable=true"

      # Dashboard
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.pi.yetanother.ca`)"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`traefik.pi.yetanother.ca`)"
      - "traefik.http.routers.traefik.entrypoints=http"
      # - "traefik.http.routers.traefik-secure.middlewares=traefik-auth" # Uncomment to require auth to access Dashboard.
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=$USER:$BASIC_AUTH_PASSWORD" # Uncomment to require auth to access Dashboard.

      # TLS
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=pi.yetanother.ca"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.pi.yetanother.ca"

      # Middleware redirect
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami:v1.9
    container_name: whoami
    command:
      - --port=41234
    labels:
      - "traefik.http.services.whoami.loadbalancer.server.port=41234"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.pi.yetanother.ca`)"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge