---
version: '3'

services:
  watchtower:
    container_name: watchtower
    environment:
      - TZ=America/Vancouver
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * 6
      - WATCHTOWER_DEBUG=true
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
