---
version: '3'

networks:
  proxy:
    external: true

services:
  mullvad-browser:
    cap_add:
      - NET_ADMIN
    container_name: mullvad-browser
    environment:
      - LOCAL_NET=192.168.0.0/16
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    image: lscr.io/linuxserver/mullvad-browser:12.5.20230702
    labels:
      - traefik.enable=true
      - traefik.http.routers.mullvad-secure.entrypoints=websecure
      - traefik.http.routers.mullvad-secure.rule=Host(`mullvad.${DOMAIN}`)
      - traefik.http.routers.mullvad-secure.service=mullvad
      - traefik.http.routers.mullvad-secure.tls=true
      - traefik.http.routers.mullvad-secure.tls.certresolver=cloudflare
      - traefik.http.services.mullvad.loadbalancer.server.port=3000
    networks:
      - proxy
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    shm_size: 1gb
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - ${DOCKER_VOLUME}/:/config:rw
      - ${DOCKER_VOLUME}/wireguard/wg0.conf:/config/wg0.conf:rw
