version: '3'

networks:
  proxy:
    external: true

services:
  portainer:
    container_name: 'portainer'
    image: 'portainer/portainer-ce:latest'
    networks:
      - 'proxy'
    restart: 'unless-stopped'
    volumes:
      - '${DOCKER_VOLUME}:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      - 'traefik.enable=true' # Enable Traefik for this service
      - 'traefik.http.routers.portainer-secure.entrypoints=websecure' # Assign the secure entrypoint for the router
      - 'traefik.http.routers.portainer-secure.rule=Host(`portainer.${DOMAIN}`)' # Set the routing rule based on the hostname
      - 'traefik.http.routers.portainer-secure.service=portainer' # Define the service for this router
      - 'traefik.http.routers.portainer-secure.tls=true' # Enable TLS for the router
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000' # Set the service's target port
