---
version: '3'

networks:
  proxy:
    external: true

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:2.18.2
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-secure.entrypoints=websecure
      - traefik.http.routers.portainer-secure.rule=Host(`portainer.${DOMAIN}`)
      - traefik.http.routers.portainer-secure.service=portainer
      - traefik.http.routers.portainer-secure.tls=true
      - traefik.http.routers.portainer-secure.tls.certresolver=cloudflare
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME}:/data
      - /var/run/docker.sock:/var/run/docker.sock
